// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDAioqHSVNEnFECTjTHEDzJzOfJYdza0',
    appId: '1:847680954307:web:90f851604080232baf2776',
    messagingSenderId: '847680954307',
    projectId: 'chat-app-51732',
    authDomain: 'chat-app-51732.firebaseapp.com',
    storageBucket: 'chat-app-51732.appspot.com',
    measurementId: 'G-93TNFKLQ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKm0j9rjIoXGidKG4LiePwnx1saTzx6BE',
    appId: '1:847680954307:android:cb40cdf798ddbad2af2776',
    messagingSenderId: '847680954307',
    projectId: 'chat-app-51732',
    storageBucket: 'chat-app-51732.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNafZNmEs64perzyi3KywW6kZShR3N_E0',
    appId: '1:847680954307:ios:f9076982dfa2ec2daf2776',
    messagingSenderId: '847680954307',
    projectId: 'chat-app-51732',
    storageBucket: 'chat-app-51732.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNafZNmEs64perzyi3KywW6kZShR3N_E0',
    appId: '1:847680954307:ios:3fd2f0a7a5a91711af2776',
    messagingSenderId: '847680954307',
    projectId: 'chat-app-51732',
    storageBucket: 'chat-app-51732.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
